### ISSUE TITLE
Notify the team when processes (Databricks calculation) fail

### ISSUE THREAD

**Issue by BjarkeMeier** [Energinet-DataHub/opengeh-wholesale#185]
Synopsis
----------------
As a team member of Mandalorian
I want to be able to be informed when a process fails
So that we can maintain and deliver a more stable process handling

Acceptance-Criteria
----------------
- [ ] The team is informed of processes that fail.
- [ ] The notification should be handled with shared application insight 

Tech Note:
---------------
It is expected that the team will be informed in the appropriate channel.

Task List
----------------
- [x] Write the teraform code needed to setup dinostic settings correct on the databricks instance on azure.
- [x] Write the terraform code neeeded to inform on teams channel via alerts 
- [x] cover calculator-job in an alert
- [x] cover integration_event_persister_job in a alert
- [x] cover time_series_igestion_job in a alert
- [x] cover publisher_job in a alert

**Comment by MadsBloendAndersen** [comment]
@lasrinnil + @johevemi will refine

**Comment by lasrinnil** [comment]
In working on this story we found a way to detect if the streaming jobs keep failing. So we now can have infinite retries and we get notified when streaming jobs are not running.

**Comment by ftoft** [comment]
It is not easy to to test because it need to get the jobs to fail.

But it is possible to make some querys in the Log Analytics workspace (appi-shared-sharedres-u-001) to test for data in the parse.
https://portal.azure.com/#@energinet.onmicrosoft.com/resource/subscriptions/3c13ff3d-aad8-4ee8-94c6-8a938ace9699/resourceGroups/rg-DataHub-SharedResouces-U-001/providers/Microsoft.OperationalInsights/workspaces/appi-shared-sharedres-u-001/logs

The alerts are created from terraform files named dbwj-alert-***.tf
In there you can se the condition and the query.

https://github.com/Energinet-DataHub/geh-timeseries/commit/7d6a793e3e26cfc71e577866442f91490948e93f#diff-a88ba2b8cebe0066c4f8bea336e5ddfdb513aa7e082878b946e62ab8575156b8
