### ISSUE TITLE
Search process screen is extended with Batch#, Period and Status

### ISSUE THREAD

**Issue by PerTHenriksen** [Energinet-DataHub/opengeh-wholesale#34]
## Description
As a PO/SME
We want to search processes and find batch #, period and status 
So that i can get some feedback on status of process

## Acceptance criteria
- [ ] Extend search process table with data in the following columns
- Batch number
- Period from 
- Period to 
- Status [Waiting, Running, Finished, Error]

**Comment by johevemi** [comment]
In the LifeCycleState: "Pending", is not returned as expected when using Jobs API 2.1, here it will return "Running". This seems to be a bug in Databricks Job API 2.1 since it works as expected in 2.0. We need to use 2.1 because of another feature added in the version, so at this time we are not able to show the status "Pending" when the Databricks run is "Pending", but will show "Running" instead.
